### ISSUE TITLE
kg command hangs

### ISSUE THREAD

**Issue by yitang** [floydwch/kaggle-cli#10]
Hi, it seems `kg` command hangs or takes longer then at least 5 minutes to run. I had to stop it and it seems got stuck with this expression 'st = os.stat(s)'. 

Here's the full traceback log.

```
Traceback (most recent call last):
  File "/usr/local/bin/kg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/kaggle_cli/main.py", line 19, in main
    return app.run(argv)
  File "/usr/local/lib/python2.7/site-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)
  File "/usr/local/lib/python2.7/site-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/kaggle_cli/config.py", line 32, in take_action
    if os.path.isdir(prefix + '.kaggle-cli'):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
KeyboardInterrupt
```

Is this problem caused by the Python distribution that I installed via home-brew on OSX?

**Comment by yitang** [comment]
After I add global configuration via 'kg config -g', =kg= command works fine.

**Comment by yitang** [comment]
okay, 'kg config' hangs.

**Comment by knguyen0105** [comment]
Running into the exact issue

This one hangs.

```
$ kg config -g -u username  -p password -c talkingdata-mobile-user-demographics
$ kg download -u username -p password -c talkingdata-mobile-user-demographics
```.

This one also hangs
`$ kg config -u username  -p password -c talkingdata-mobile-user-demographics
`

**Comment by floydwch** [comment]
I find a bug in the path search, https://github.com/floydwch/kaggle-cli/commit/f5b56e02442a25dee794c6ab21dd2a90f7f7f09d .

The latest version might fix this issue. Please try to reinstall it.

**Comment by knguyen0105** [comment]
It Worked. Thanks much.

**Comment by stas-sl** [comment]
Hi, version 0.4.1 still hangs for me on amazon EC2

```
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/bin/kg", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/kaggle_cli/main.py", line 19, in main
    return app.run(argv)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/kaggle_cli/submit.py", line 28, in take_action
    if os.path.isdir(prefix + '.kaggle-cli'):
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
KeyboardInterrupt
```

**Comment by floydwch** [comment]
@stas-sl What's the current working dir?

I guess you would issue the command outside your home dir?

**Comment by stas-sl** [comment]
I have a symlink that is in home dir but it points to a dir that is outside home:
~/my-project/submissions -> /mnt/submissions
So I'm trying to run the command from ~/my-project/submissions dir. Though it works ok, if I run it from ~/my-project

**Comment by floydwch** [comment]
So, do you mean the issue occurred when you were under `/mnt/` ?

**Comment by stas-sl** [comment]
No, actual working dir was ~/my-project/submissions. But it seems that it matters that it is not usual dir but a symlink (to folder outside home dir).

**Comment by floydwch** [comment]
@stas-sl  Hmm.. Thanks for your report!

**Comment by floydwch** [comment]
@stas-sl I found something wrong, could you try the latest one?

**Comment by stas-sl** [comment]
Now I get the following error if I have username and password in global config **~/.kaggle-cli/config** and run the command from **~/my-project/submissions**:
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/bin/kg", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/kaggle_cli/main.py", line 19, in main
    return app.run(argv)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/app.py", line 226, in run
    result = self.run_subcommand(remainder)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/app.py", line 346, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/cliff/command.py", line 55, in run
    self.take_action(parsed_args)
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/kaggle_cli/download.py", line 89, in take_action
    browser['UserName'] = username
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/mechanize/_form.py", line 2782, in __setitem__
    control.value = value
  File "/home/ubuntu/.pyenv/versions/anaconda2-4.0.0/lib/python2.7/site-packages/mechanize/_form.py", line 1217, in __setattr__
    raise TypeError("must assign a string")
TypeError: must assign a string
```

Though, if I have local config in **~/my-project/submissions/.kaggle-cli/config** or if I run command from **~/my-project** it works ok.

**Comment by floydwch** [comment]
I rewrote the problematic config, see https://github.com/floydwch/kaggle-cli/commit/ddc71bb7e28811a305758fe983a721341f29a4e0 .

And cleaning the issue list, if you still have the problem, please open a new issue.
