### ISSUE TITLE
'html5lib.treebuilders' has no attribute '_base' on submission

### ISSUE THREAD

**Issue by IoDmitri** [floydwch/kaggle-cli#38]
While trying to make a submission by running `submit <my_csv_file> -m "some notes", I get the following printout. 
```
Traceback (most recent call last):
  File "/usr/local/bin/kg", line 9, in <module>
    load_entry_point('kaggle-cli==0.10.0', 'console_scripts', 'kg')()
  File "/usr/local/lib/python3.5/dist-packages/kaggle_cli/main.py", line 21, in main
    return app.run(argv)
  File "/usr/local/lib/python3.5/dist-packages/cliff/app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "/usr/local/lib/python3.5/dist-packages/cliff/app.py", line 363, in run_subcommand
    subcommand = self.command_manager.find_command(argv)
  File "/usr/local/lib/python3.5/dist-packages/cliff/commandmanager.py", line 83, in find_command
    cmd_factory = cmd_ep.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/kaggle_cli/submit.py", line 3, in <module>
    from . import common
  File "/usr/local/lib/python3.5/dist-packages/kaggle_cli/common.py", line 3, in <module>
    from mechanicalsoup import Browser
  File "/usr/local/lib/python3.5/dist-packages/mechanicalsoup/__init__.py", line 2, in <module>
    from .browser import Browser
  File "/usr/local/lib/python3.5/dist-packages/mechanicalsoup/browser.py", line 3, in <module>
    import bs4
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```

**Comment by greenyouse** [comment]
This might be a problem with html5lib. I used the first [suggested fix from SO](https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base#38799613) and it solved the problem for me.

I think [this](https://bugs.launchpad.net/beautifulsoup/+bug/1603299) is the relevant problem from html5lib.

**Comment by floydwch** [comment]
@greenyouse lol, thanks for your find, I guess it won't occur if install via `pip install -U kaggle-cli`.

**Comment by seansio1995** [comment]
Thanks, it helps
